include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    prefer_const_constructors_in_immutables: true
    camel_case_types: true
    sort_constructors_first: true
    no_logic_in_create_state: true
    always_use_package_imports: true
    always_put_required_named_parameters_first: true
    avoid_positional_boolean_parameters: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.graphql.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
