name: flutter_image_cropper_plus
description: "Flutter plugin that provides image cropping functionality. It is designed to be easy to use and flexible, allowing developers to customize the cropping experience for their specific needs. The plugin supports both Android and iOS platforms, and it's built with Kotlin, Java, and Dart, using Gradle and Pub as package managers."
version: 0.0.1
homepage: https://github.com/dwikyhardi/flutter_image_cropper_plus

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  plugin:
    platforms:
      android:
        package: id.my.dwiky.flutter_image_cropper_plus
        pluginClass: FlutterImageCropperPlusPlugin
      ios:
        pluginClass: FLTImageCropperPlusPlugin

